### ISSUE TITLE
Does it seem that the methodology section was omitted from the arxiv paper?

### ISSUE THREAD

**Issue by syguan96** [HaozheZhao/UltraEdit#1]
Nice work! May I ask about the schedule for method release?

**Comment by HaozheZhao** [comment]
We have release the code of the data generation method in the folder of ```data_generation```.

You can just run the ```run_sdxl_turbo_p2p_i2i_8gpu.sh``` and  ```run_inpainting_multiiple_objects.sh``` to get the free-form and region-based image editing data. 

 The detailed illustrations about the generation code and the jsonl files of the generated editing prompts for editing pair generation will be uploaded soon.
