### ISSUE TITLE
The demo has stopped working.

### ISSUE THREAD

**Issue by sp1cae** [HaozheZhao/UltraEdit#14]
![20240806-101550](https://github.com/user-attachments/assets/7d867a4b-c0bd-49dc-ac46-580ef1b342eb)

**Comment by HaozheZhao** [comment]
Thank you for notifying us! 
We are utilizing free GPUs provided by Zero Space, and occasionally, there may be no GPUs available for this demo.
I have restarted the demo, and it is now back online.
