### ISSUE TITLE
ImagenHub Integration

### ISSUE THREAD

**Issue by vinesmsuic** [HaozheZhao/UltraEdit#4]
Very cool work!

We added the implementation of UltraEdit on [ImagenHub (ICLR 2024)](https://github.com/TIGER-AI-Lab/ImagenHub). Feel free to checkout the results on our ImagenHub benchmark and verify the code implementation :)

- Visualization: https://chromaica.github.io/Museum/ImagenHub_Text-Guided_IE/
- Code integration: https://github.com/TIGER-AI-Lab/ImagenHub/pull/30

Best,
Max

**Comment by chenllliang** [comment]
It seems awesome!

**Comment by HaozheZhao** [comment]
Hi Max,

Thanks for your message and the opportunity to work on ImagenHub!

We noticed a minor issue with the model inference for the free-form image editing setting in the ImageHub. After training with the region-based image editing data, the model has become quite sensitive to the mask input. Hence, when using the model for free-form image editing, we recommend setting a higher SFG scale, such as 10.5 or above, for better results when providing the model with a blank mask.

Alternatively, you can use this [model](https://huggingface.co/BleachNick/SD3_UltraEdit_freeform) that has been trained specifically with only free-form image editing dataset which does not support the mask input. During the inference of this model, you can just set the mask_img to be None.

**Comment by vinesmsuic** [comment]
Now its changed to the free-form model!
https://github.com/TIGER-AI-Lab/ImagenHub/pull/33

We also re-run the experiment on Visualization: https://chromaica.github.io/Museum/ImagenHub_Text-Guided_IE/
