### ISSUE TITLE
Why are there always errors when loading the model, no matter how many times the model is re-downloaded?

### ISSUE THREAD

**Issue by JohnsonXi** [HaozheZhao/UltraEdit#9]
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/910c3bcd-7acf-4fec-9d40-bc8f4f3f654c">
As shown in the image, this download is very complete, with no interruptions, but the error still occurs.
**Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 960 column 3**
Please check if the issue is due to corrupted weights from Hugging Face, or some other problem.

**Comment by HaozheZhao** [comment]
It seems to be the problem due to the version of the transformers.

#https://github.com/huggingface/diffusers/issues/8495

Maybe update the transformers will be the soluation. 

```pip install transformers -U```
